# Makefile.in generated by automake 1.11.3 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/multi2sim
pkgincludedir = $(includedir)/multi2sim
pkglibdir = $(libdir)/multi2sim
pkglibexecdir = $(libexecdir)/multi2sim
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/configure \
	$(top_srcdir)/src/Makefile.in \
	$(top_srcdir)/src/arch/Makefile.in \
	$(top_srcdir)/src/arch/arm/Makefile.in \
	$(top_srcdir)/src/arch/arm/asm/Makefile.in \
	$(top_srcdir)/src/arch/arm/emu/Makefile.in \
	$(top_srcdir)/src/arch/arm/timing/Makefile.in \
	$(top_srcdir)/src/arch/evergreen/Makefile.in \
	$(top_srcdir)/src/arch/evergreen/asm/Makefile.in \
	$(top_srcdir)/src/arch/evergreen/emu/Makefile.in \
	$(top_srcdir)/src/arch/evergreen/timing/Makefile.in \
	$(top_srcdir)/src/arch/fermi/Makefile.in \
	$(top_srcdir)/src/arch/fermi/asm/Makefile.in \
	$(top_srcdir)/src/arch/fermi/emu/Makefile.in \
	$(top_srcdir)/src/arch/fermi/timing/Makefile.in \
	$(top_srcdir)/src/arch/southern-islands/Makefile.in \
	$(top_srcdir)/src/arch/southern-islands/asm/Makefile.in \
	$(top_srcdir)/src/arch/southern-islands/emu/Makefile.in \
	$(top_srcdir)/src/arch/southern-islands/timing/Makefile.in \
	$(top_srcdir)/src/arch/x86/Makefile.in \
	$(top_srcdir)/src/arch/x86/asm/Makefile.in \
	$(top_srcdir)/src/arch/x86/emu/Makefile.in \
	$(top_srcdir)/src/arch/x86/timing/Makefile.in \
	$(top_srcdir)/src/lib/Makefile.in \
	$(top_srcdir)/src/lib/esim/Makefile.in \
	$(top_srcdir)/src/lib/mhandle/Makefile.in \
	$(top_srcdir)/src/lib/misc/Makefile.in \
	$(top_srcdir)/src/lib/struct/Makefile.in \
	$(top_srcdir)/src/mem-system/Makefile.in \
	$(top_srcdir)/src/network/Makefile.in \
	$(top_srcdir)/src/visual/Makefile.in \
	$(top_srcdir)/src/visual/common/Makefile.in \
	$(top_srcdir)/src/visual/evergreen/Makefile.in \
	$(top_srcdir)/src/visual/memory/Makefile.in \
	$(top_srcdir)/src/visual/x86/Makefile.in AUTHORS COPYING \
	ChangeLog INSTALL NEWS TODO depcomp install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES = src/Makefile src/arch/Makefile \
	src/mem-system/Makefile src/network/Makefile \
	src/arch/arm/Makefile src/arch/arm/asm/Makefile \
	src/arch/arm/emu/Makefile src/arch/arm/timing/Makefile \
	src/arch/evergreen/Makefile src/arch/evergreen/asm/Makefile \
	src/arch/evergreen/emu/Makefile \
	src/arch/evergreen/timing/Makefile src/arch/fermi/Makefile \
	src/arch/fermi/asm/Makefile src/arch/fermi/emu/Makefile \
	src/arch/fermi/timing/Makefile \
	src/arch/southern-islands/Makefile \
	src/arch/southern-islands/asm/Makefile \
	src/arch/southern-islands/emu/Makefile \
	src/arch/southern-islands/timing/Makefile \
	src/arch/x86/Makefile src/arch/x86/asm/Makefile \
	src/arch/x86/emu/Makefile src/arch/x86/timing/Makefile \
	src/visual/Makefile src/visual/common/Makefile \
	src/visual/evergreen/Makefile src/visual/memory/Makefile \
	src/visual/x86/Makefile src/lib/Makefile src/lib/esim/Makefile \
	src/lib/mhandle/Makefile src/lib/misc/Makefile \
	src/lib/struct/Makefile
CONFIG_CLEAN_VPATH_FILES =
SOURCES =
DIST_SOURCES =
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(pkgdata_imagesdir)"
DATA = $(pkgdata_images_DATA)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
AM_RECURSIVE_TARGETS = $(RECURSIVE_TARGETS:-recursive=) \
	$(RECURSIVE_CLEAN_TARGETS:-recursive=) tags TAGS ctags CTAGS \
	distdir dist dist-all distcheck
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /media/_home/vicent/gap/prefetch/multi2sim/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AUTOCONF = ${SHELL} /media/_home/vicent/gap/prefetch/multi2sim/missing --run autoconf
AUTOHEADER = ${SHELL} /media/_home/vicent/gap/prefetch/multi2sim/missing --run autoheader
AUTOMAKE = ${SHELL} /media/_home/vicent/gap/prefetch/multi2sim/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -O3 -std=gnu99 -DNDEBUG
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DATADIR = ${prefix}/share
DEFS = -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"multi2sim\" -DVERSION=\"3.3\" -DSTDC_HEADERS=1 -DHAVE_SYS_WAIT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_FCNTL_H=1 -DHAVE_FLOAT_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_IOCTL_H=1 -DHAVE_SYS_SOCKET_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_UTIME_H=1 -DHAVE_ELF_H=1 -DHAVE_ZLIB_H=1 -DHAVE_LIBZ=1 -DHAVE_GLUT_H=1 -DHAVE_LIBGLUT=1 -DHAVE_LIBGL=1 -DHAVE_LIBGLU=1 -DHAVE_STRUCT_STAT_ST_BLKSIZE=1 -DHAVE_STRUCT_STAT_ST_BLOCKS=1 -DHAVE_ST_BLOCKS=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DHAVE_UNISTD_H=1 -DHAVE_CHOWN=1 -DLSTAT_FOLLOWS_SLASHED_SYMLINK=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_MMAP=1 -DHAVE_STDLIB_H=1 -DHAVE_REALLOC=1 -DHAVE_ALARM=1 -DHAVE_BZERO=1 -DHAVE_FTRUNCATE=1 -DHAVE_GETCWD=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MEMSET=1 -DHAVE_MKDIR=1 -DHAVE_MUNMAP=1 -DHAVE_SELECT=1 -DHAVE_SOCKET=1 -DHAVE_STRCASECMP=1 -DHAVE_STRCHR=1 -DHAVE_STRDUP=1 -DHAVE_STRNCASECMP=1 -DHAVE_STRTOL=1 -DHAVE_UTIME=1 -DHAVE_LIBM=1 -DHAVE_GTK=1
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
GTK_CFLAGS = -pthread -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12  
GTK_LIBS = -lgtk-3 -lgdk-3 -latk-1.0 -lgio-2.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lpango-1.0 -lcairo -lgobject-2.0 -lglib-2.0  
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lm -lGLU -lGL -lglut -lz 
LTLIBOBJS = 
M2S_INCLUDES =  -I$(top_srcdir)/src/lib/esim -I$(top_srcdir)/src/lib/mhandle -I$(top_srcdir)/src/lib/misc -I$(top_srcdir)/src/lib/struct -I$(top_srcdir)/src/arch/arm/asm -I$(top_srcdir)/src/arch/arm/emu -I$(top_srcdir)/src/arch/arm/timing -I$(top_srcdir)/src/arch/evergreen/asm -I$(top_srcdir)/src/arch/evergreen/emu -I$(top_srcdir)/src/arch/evergreen/timing -I$(top_srcdir)/src/arch/fermi/asm -I$(top_srcdir)/src/arch/fermi/emu -I$(top_srcdir)/src/arch/fermi/timing -I$(top_srcdir)/src/arch/southern-islands/asm -I$(top_srcdir)/src/arch/southern-islands/emu -I$(top_srcdir)/src/arch/southern-islands/timing -I$(top_srcdir)/src/arch/x86/asm -I$(top_srcdir)/src/arch/x86/emu -I$(top_srcdir)/src/arch/x86/timing -I$(top_srcdir)/src/visual/common -I$(top_srcdir)/src/visual/evergreen -I$(top_srcdir)/src/visual/memory -I$(top_srcdir)/src/visual/x86 -I$(top_srcdir)/src/mem-system -I$(top_srcdir)/src/network 
MAKEINFO = ${SHELL} /media/_home/vicent/gap/prefetch/multi2sim/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = multi2sim
PACKAGE_BUGREPORT = 
PACKAGE_NAME = 
PACKAGE_STRING = 
PACKAGE_TARNAME = 
PACKAGE_URL = 
PACKAGE_VERSION = 
PATH_SEPARATOR = :
PKGDATADIR = ${datarootdir}/multi2sim
PKG_CONFIG = /usr/bin/pkg-config
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 3.3
abs_builddir = /media/_home/vicent/gap/prefetch/multi2sim
abs_srcdir = /media/_home/vicent/gap/prefetch/multi2sim
abs_top_builddir = /media/_home/vicent/gap/prefetch/multi2sim
abs_top_srcdir = /media/_home/vicent/gap/prefetch/multi2sim
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /media/_home/vicent/gap/prefetch/multi2sim/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
SUBDIRS = src
images = \
	images/alu_engine.png \
	images/cf_engine.png \
	images/tex_engine.png \
	images/m2s-icon.png \
	images/close.png \
	images/close-sel.png \
	\
	images/back-single.png \
	images/back-double.png \
	images/back-triple.png \
	images/forward-single.png \
	images/forward-double.png \
	images/forward-triple.png \
	images/go.png

pkgdata_imagesdir = $(pkgdatadir)/images
pkgdata_images_DATA = ${images}
EXTRA_DIST = \
	tools/m2s-opencl-kc/debug.c \
	tools/m2s-opencl-kc/debug.h \
	tools/m2s-opencl-kc/elfanalyze.c \
	tools/m2s-opencl-kc/elfanalyze.h \
	tools/m2s-opencl-kc/m2s-opencl-kc.c \
	tools/m2s-opencl-kc/Makefile \
	tools/m2s-opencl-kc/misc.c \
	tools/m2s-opencl-kc/misc.h \
	\
	tools/libm2s-glut/glut.c \
	tools/libm2s-glut/Makefile \
	tools/libm2s-glut/m2s-glut.h \
	tools/libm2s-glut/window.c \
	\
	tools/libm2s-opencl/CL/cl_platform.h \
	tools/libm2s-opencl/CL/cl_ext.h \
	tools/libm2s-opencl/CL/opencl.h \
	tools/libm2s-opencl/CL/cl.h \
	tools/libm2s-opencl/CL/cl_gl.h \
	tools/libm2s-opencl/CL/cl_gl_ext.h \
	tools/libm2s-opencl/command-queue.c \
	tools/libm2s-opencl/context.c \
	tools/libm2s-opencl/device.c \
	tools/libm2s-opencl/event.c \
	tools/libm2s-opencl/kernel.c \
	tools/libm2s-opencl/m2s-opencl.c \
	tools/libm2s-opencl/m2s-opencl.h \
	tools/libm2s-opencl/Makefile \
	tools/libm2s-opencl/mem.c \
	tools/libm2s-opencl/platform.c \
	tools/libm2s-opencl/program.c \
	tools/libm2s-opencl/sampler.c \
	\
	tools/libm2s-opengl/m2s-opengl.h \
	tools/libm2s-opengl/opengl.c \
	tools/libm2s-opengl/Makefile \
	\
	tools/libm2s-cuda/m2s-cuda.h \
	tools/libm2s-cuda/cuda.c \
	tools/libm2s-cuda/Makefile \
	\
	tools/libm2s-cudart/m2s-cudart.h \
	tools/libm2s-cudart/cudart.c \
	tools/libm2s-cudart/Makefile \
	\
	tools/barplot/barplot.py \
	\
	tools/inifile/inifile.py \
	\
	tools/m2s-pipeline/m2s-pipeline.c \
	tools/m2s-pipeline/Makefile \
	\
	samples/cpuconfig.args-sort \
	samples/ctxconfig.args-sort \
	samples/test-args.c \
	samples/test-args.i386 \
	samples/test-sort.c \
	samples/test-sort.i386 \
	\
	samples/memconfig-eg1/cpu-config \
	samples/memconfig-eg1/mem-config \
	\
	samples/memconfig-eg2/cpu-config \
	samples/memconfig-eg2/mem-config \
	samples/memconfig-eg2/net-config \
	\
	samples/memconfig-eg3/cpu-config \
	samples/memconfig-eg3/mem-config \
	samples/memconfig-eg3/net-config \
	\
	samples/memconfig-eg4/cpu-config \
	samples/memconfig-eg4/gpu-config \
	samples/memconfig-eg4/mem-config \
	\
	${images}

all: all-recursive

.SUFFIXES:
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
src/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/mem-system/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/mem-system/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/network/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/network/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/arm/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/arm/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/arm/asm/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/arm/asm/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/arm/emu/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/arm/emu/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/arm/timing/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/arm/timing/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/evergreen/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/evergreen/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/evergreen/asm/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/evergreen/asm/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/evergreen/emu/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/evergreen/emu/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/evergreen/timing/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/evergreen/timing/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/fermi/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/fermi/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/fermi/asm/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/fermi/asm/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/fermi/emu/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/fermi/emu/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/fermi/timing/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/fermi/timing/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/southern-islands/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/southern-islands/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/southern-islands/asm/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/southern-islands/asm/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/southern-islands/emu/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/southern-islands/emu/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/southern-islands/timing/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/southern-islands/timing/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/x86/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/x86/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/x86/asm/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/x86/asm/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/x86/emu/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/x86/emu/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/arch/x86/timing/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/arch/x86/timing/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/visual/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/visual/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/visual/common/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/visual/common/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/visual/evergreen/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/visual/evergreen/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/visual/memory/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/visual/memory/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/visual/x86/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/visual/x86/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/lib/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/lib/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/lib/esim/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/lib/esim/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/lib/mhandle/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/lib/mhandle/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/lib/misc/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/lib/misc/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
src/lib/struct/Makefile: $(top_builddir)/config.status $(top_srcdir)/src/lib/struct/Makefile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
install-pkgdata_imagesDATA: $(pkgdata_images_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(pkgdata_imagesdir)" || $(MKDIR_P) "$(DESTDIR)$(pkgdata_imagesdir)"
	@list='$(pkgdata_images_DATA)'; test -n "$(pkgdata_imagesdir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgdata_imagesdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgdata_imagesdir)" || exit $$?; \
	done

uninstall-pkgdata_imagesDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgdata_images_DATA)'; test -n "$(pkgdata_imagesdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pkgdata_imagesdir)'; $(am__uninstall_files_from_dir)

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(DATA)
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(pkgdata_imagesdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-generic mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-generic distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-pkgdata_imagesDATA

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am:

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-generic

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-pkgdata_imagesDATA

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) ctags-recursive \
	install-am install-strip tags-recursive

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am am--refresh check check-am clean clean-generic \
	ctags ctags-recursive dist dist-all dist-bzip2 dist-gzip \
	dist-lzip dist-lzma dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-generic distclean-tags \
	distcleancheck distdir distuninstallcheck dvi dvi-am html \
	html-am info info-am install install-am install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-pkgdata_imagesDATA install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	installdirs-am maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-generic pdf pdf-am ps ps-am tags \
	tags-recursive uninstall uninstall-am \
	uninstall-pkgdata_imagesDATA


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
